import type { Author } from './types'
import { countries } from './data'

const API = 'https://www.wikidata.org/w/api.php'
const TARGET_SIZE = 500
let catalogPromise: Promise<Author[]> | null = null
export let globalAuthors: Author[] = []
type Entity = { id: string; labels?: Record<string,{value:string}>; descriptions?: Record<string,{value:string}>; claims?: Record<string,Array<{mainsnak?:{datavalue?:{value:any}}}>> }
function era(year: number) { if (year < 500) return '古典时代'; if (year < 1400) return '中世纪'; if (year < 1700) return '文艺复兴'; if (year < 1800) return '启蒙时代'; if (year < 1900) return '19世纪'; if (year < 1950) return '现代'; return '当代' }
function localized(record?: Record<string,{value:string}>) { return record?.zh?.value || record?.['zh-hans']?.value || record?.en?.value || '' }
function claimValue(entity: Entity, property: string) { return entity.claims?.[property]?.[0]?.mainsnak?.datavalue?.value }
function claimYear(entity: Entity, property: string) { const time = claimValue(entity, property)?.time; const match = typeof time === 'string' && time.match(/[-+](\d{1,4})-/); return match ? Number(match[1]) : undefined }
function entityId(entity: Entity, property: string) { return claimValue(entity, property)?.id as string | undefined }
function makeAuthor(entity: Entity, countryLabels: Map<string,string>): Author | null { const name = localized(entity.labels); const birthYear = claimYear(entity,'P569'); if (!name || !birthYear) return null; const countryName = countryLabels.get(entityId(entity,'P27') || '') || '世界文学'; const matched = countries.find(country=>country.name===countryName); const imageFile = claimValue(entity,'P18') as string | undefined; return { id:`wikidata-${entity.id}`, name, originalName:name, country:countryName, countryCode:matched?.id || 'global', era:era(birthYear), birthYear, deathYear:claimYear(entity,'P570'), portrait:name.slice(0,1), portraitUrl:imageFile ? `https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(imageFile)}?width=600` : undefined, sourceUrl:`https://www.wikidata.org/wiki/${entity.id}`, shortBio:localized(entity.descriptions) || '世界文学中的重要写作者。', lifeStory:`${name}的生平与创作资料由公开知识库持续整理。`, works:[{title:'代表作品待核',note:'进入详情页后自动检索公开百科资料。'},{title:'重要作品待核',note:'作品信息以公开来源的最新条目为准。'},{title:'作品选集待核',note:'建议编辑校对后作为正式展陈内容。'}], influence:'其作品与思想在文学史中具有可考据的影响，详情页将显示公开资料摘要。', value:'通过可靠来源持续补充，让文学史中的多元声音被看见。', genres:['文学'], timeline:[{year:String(birthYear),title:'诞生',description:'公开知识库记录的出生年份。'}], relatedAuthors:[], influenceLevel:4 } }
async function getJson(params: Record<string,string>) { const url = `${API}?${new URLSearchParams({...params,format:'json',origin:'*'}).toString()}`; let lastError: unknown; for(let attempt=0;attempt<3;attempt++){ const controller=new AbortController(); const timeout=window.setTimeout(()=>controller.abort(),12000); try { const response = await fetch(url,{cache:'no-store',signal:controller.signal}); if(!response.ok) throw new Error(`Wikidata request failed: ${response.status}`); return await response.json() } catch(error) { lastError=error; if(attempt<2) await new Promise(resolve=>setTimeout(resolve,350*(attempt+1))) } finally { window.clearTimeout(timeout) } } throw lastError }
async function searchWriterIds() { const offsets = Array.from({length:10},(_,index)=>String(index*50)); const pages = await Promise.all(offsets.map(sroffset=>getJson({action:'query',list:'search',srsearch:'haswbstatement:P106=Q49757',srnamespace:'0',srlimit:'50',sroffset}))); return [...new Set(pages.flatMap(page=>page.query?.search?.map((item:{title:string})=>item.title) || []))].slice(0,TARGET_SIZE) }
async function getEntities(ids:string[], languages='zh|zh-hans|en') { const batches = Array.from({length:Math.ceil(ids.length/50)},(_,index)=>ids.slice(index*50,index*50+50)); const pages = await Promise.all(batches.map(batch=>getJson({action:'wbgetentities',ids:batch.join('|'),props:'labels|descriptions|claims',languages}))); return pages.flatMap(page=>Object.values(page.entities || {}) as Entity[]) }
async function requestCatalog() { try { const ids=await searchWriterIds(); if(ids.length<TARGET_SIZE)return []; const entities=await getEntities(ids); const countryIds=[...new Set(entities.map(entity=>entityId(entity,'P27')).filter(Boolean) as string[])]; const countryEntities=countryIds.length?await getEntities(countryIds):[]; const countryLabels=new Map(countryEntities.map(entity=>[entity.id,localized(entity.labels)])); const authors=entities.map(entity=>makeAuthor(entity,countryLabels)).filter(Boolean) as Author[]; const unique=[...new Map(authors.map(author=>[author.id,author])).values()]; return unique.length>=TARGET_SIZE?unique.slice(0,TARGET_SIZE):[] } catch { return [] } }
export function fetchGlobalWriters() { if(!catalogPromise)catalogPromise=requestCatalog().then(result=>{globalAuthors=result;return result}); return catalogPromise }
